name: Release
on:
  push:
    branches:
      - beta-release
      - release

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '20'
          cache: 'npm'
      - name: NPM Install
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          npm install --save-dev firebase-tools
          ./node_modules/.bin/firebase use production
          ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN --non-interactive --only hosting
