name: CI Policies
on: pull_request

jobs:
  enforce-release-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Print base ref and head ref
        run: |
          echo "Your head ref is ${{ github.head_ref }}."
          echo "Your base ref is ${{ github.base_ref }}."
      - name: Fail if try to push release from non-main branch
        if: ((github.base_ref == 'beta-release' || github.base_ref == 'release') && github.head_ref != 'main')
        run: |
          echo "Head ref must be main for release. Everything should go through staging first!"
          exit 1
  # warn-big-diff:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: cornell-dti/big-diff-warning@master
  #       env:
  #         BOT_TOKEN: '${{ secrets.BOT_TOKEN }}'
